### ISSUE TITLE
Feature Request: GUI for the application

### ISSUE THREAD

**Issue by Twig6943** [zb3/gnome-gamma-tool#20]
title.

**Comment by zb3** [comment]
Apart from my ultimate laziness, I didn't even plan any GUI because:
- the change can't be applied instantly, so it's not possible to make a slider where you see the live preview of the gamma
- I see this tool as working like "fire and forget" - you download it, try few values for gamma to calibrate it, the profile is written and then you can remove ggt and the new settings continue to work

Hence I see that GUI'd not be any game changer and'd complicate the app, so my laziness will not let me implement that.
I think GUI could belong in a separate app like gnome-gamma-tool-gui or something
