### ISSUE TITLE
Tool worked three times only

### ISSUE THREAD

**Issue by mzryz** [zb3/gnome-gamma-tool#21]
Hello there,

I am attempting to use this software on Manjaro Linux. I have been simply only attempting to change gamma with the following:

`./gnome-gamma-tool.py -g 0.8`

I tried a few different variations of gamma, to see which I liked, it worked about 3 times. Each time I said 'N' to saving my settings. But now the program has no effect on screen brightness at all. I even rebooted my computer.

I tried changing contrast, which oddly, still works. But it ignores the gamma value each time.

Intel GPU on Wayland. Gnome version 45.4.

**Comment by zb3** [comment]
Does it also ignore gamma if you set it to a value you didn't set earlier?
Does
```
rm .local/share/icc/gnome-gamma-tool-*
rm .local/share/icc/.goutputstream-*
```
help?

After you create the profile with GGT, do you see it in Settings -> Color panel?
I remember that I sometimes had to click on the correct profile multiple times, but since you say contrast works.. this confuses me :O

**Comment by mzryz** [comment]
Hi zb3,

I think removing those files might have fixed it. Although I could have sworn that my terminal said that no files were found. Anyway, after doing that, I seem to be able to change my gamma fine. I just went from 0.3>0.9 pressing 'N' each time and so far it seems OK.

I guess I'll close this? But I'm as confused as you :)
