### ISSUE TITLE
Failing with "The profile was not added in time"

### ISSUE THREAD

**Issue by MatthewScholefield** [zb3/gnome-gamma-tool#7]
Hi, great project! I can't seem to get it to work on my system. Here is the output:

```
$ ./gnome-gamma-tool.py -g 0.8 
Current profile is /home/matthew/.local/share/icc/edid-f17676179651299583cd4294bff1d6e2.icc
Traceback (most recent call last):
  File "/home/matthew/Compile/gnome-gamma-tool/./gnome-gamma-tool.py", line 350, in <module>
    main()
  File "/home/matthew/Compile/gnome-gamma-tool/./gnome-gamma-tool.py", line 333, in main
    new_profile = mgr.new_profile_with_name(profile_data, OUR_PREFIX + unique_id)
  File "/home/matthew/Compile/gnome-gamma-tool/./gnome-gamma-tool.py", line 248, in new_profile_with_name
    new_profile = self.cd.import_profile_sync(Gio.File.new_for_path(tmp_path))
gi.repository.GLib.GError: cd_client_error: The profile was not added in time (0)
```

GNOME Version: `42.5`
OS: `Ubuntu 22.04` (technically Pop!_OS, but using GNOME shell)
Laptop: `Zephyrus G14 GA402RJ`

Any idea if there's a simple problem this could be?

**Comment by MatthewScholefield** [comment]
Update: I can manually apply the generated profiles in the system color settings which is a good workaround for now.

**Comment by zb3** [comment]
Thanks the report, I was able to reproduce the bug on the latest Pop!_OS. However, debugging this one was a bit challenging and I'm still not sure what the underlying problem actually is and what's the easiest way to fix it. I'll look into this tomorrow, but feel free to help :)

So it appears that `import_profile_sync` first copies the profile file to the `$XDG_DATA_HOME/icc` directory, then waits for the other part of colord to pick up that file (via inotify), then calls `find_profile_by_filename` to retrieve the profile handle.

And it turns out that on that Pop!_OS instance, the profile file is not recognized after creating the new profile file and then writing to it, hence a timeout occurs.
HOWEVER, surprisingly, the profile is recognized after that file is then manually renamed.

Looking at colord code, one guess is that it could be an exotic instance of a race condition, like this:
1. New profile file is open for writing
2. Inotify create event is caught by colord, but the file is empty, so no profile added
3. The file is written and closed.
4. Colord only cares about the creation event (https://github.com/hughsie/colord/blob/be3aa625c10e9f1053c520d2cf849332cb535bd4/lib/colord/cd-icc-store.c#L338)

But why is it that that scenario never happens on my machine, yet always happens on that Pop!_OS instance? If I get more time, this might be interesting to investigate..

**Comment by zb3** [comment]
Now about the fix. I guess the profile file needs to be manually copied to that directory, then renamed (I can't fix colord, so ggt will do this). But my initial implementation doesn't work as ggt somehow needs to wait for the profile to be recognized, mimicking the behaviour of colord.

**Comment by zb3** [comment]
@MatthewScholefield, could you please test whether the https://github.com/zb3/gnome-gamma-tool/tree/fix-import branch works? While I'm able to test this in a Pop!_OS VM, I can't confirm the final effect.
